spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
